spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.200:3309/finance_dev?serverTimeZone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    com:
      yunyun:
        financemanager:
          project:
            mapper: debug

